### ISSUE TITLE
Miele Cloud Binding on OpenHab Docker cannot authorize due to too many threads required

### ISSUE THREAD

**Issue by robkamp** [openhab/openhab-distro#1596]
When trying to authenticate for the Miele Cloud binding using containerized OpenHAB (Docker) it fails with the following error in the log file.

`Insufficient configured threads: required=16 < max=10 for QueuedThreadPool[OH-httpClient-OAuthConnector]`

```
runtimeInfo:
  version: 4.1.0
  buildString: "Build #3680"
locale: nl-NL
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.8
  javaVendor: Alpine
  osName: Linux
  osVersion: 6.1.50-production+truenas
  osArchitecture: amd64
  availableProcessors: 32
  freeMemory: 228349472
  totalMemory: 620756992
  uptime: 48828
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-astro
  - binding-bigassfan
  - binding-chromecast
  - binding-mielecloud
  - binding-network
  - binding-nibeuplink
  - binding-openweathermap
  - binding-solaredge
  - binding-tradfri
  - binding-zwave
  - misc-homekit
  - persistence-influxdb
  - persistence-rrd4j
  - transformation-map
  - ui-basic
  - ui-habpanel
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 8
    language: nl-NL
    languages:
      - nl-NL
      - nl
      - en-US
      - en
      - de
    onLine: true
    platform: MacIntel
  screen:
    width: 1680
    height: 1050
    colorDepth: 30
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
timestamp: 2023-10-20T08:34:31.427Z
```
