### ISSUE TITLE
First startup is not doing its job (snapshot 1104 or 1119)

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-distro#602]
@kaikreuzer : With the distribution 1119 (I got already the same behaviour with the distribution 1104), the first startup ends with a log entry saying that the minimal package has been installed and then nothing happens even after several minutes. Nothing is really installed and started.

Hopefully the workaround is easy, I just stop and restart and then everything starts as expected.

I am starting a new distribution from scratch with my usual setup files.

**Comment by martinvw** [comment]
Now you mention I think I had the same problem with my docker, I also doubted whether it was related to some bindings in the addons folder.

@lolodomo do you have an empty addons folder?

**Comment by lolodomo** [comment]
Yes, when I install a new version, I start with an empty addons folder.

**Comment by lolodomo** [comment]
@kaikreuzer : did you notice this issue ?

**Comment by martinvw** [comment]
@wborn did you also experience this or was I just not patient enough?

**Comment by wborn** [comment]
All works fine for me @martinvw with a barebones docker-compose.yml like this:

```
version: "2.1"

services:
  openhab:
    container_name: openhab-test
    image: "openhab/openhab:2.2.0-snapshot-amd64-debian"
    network_mode: host
    restart: unless-stopped
    stdin_open: true
    tty: true
```

I'm using:
* Docker version 17.09.0-ce, build afdb6d4
* docker-compose version 1.17.1, build 6d101fb

I always forget to upgrade docker-compose. They are making progress there too with improvements and issue fixing! ;-)
